name: Build and Release HellCore Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - "Alpha"

jobs:
  build-alpha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout HellCore Launcher
        uses: actions/checkout@v4
        with:
          repository: hell-core/hellcore-launcher
          ref: master
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1

      - name: Install system dependencies for Tauri (GTK/GLib)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            pkg-config \
            build-essential \
            libssl-dev \
            libdbus-1-dev \
            libgdk-pixbuf2.0-dev \
            libwebkit2gtk-4.0-dev

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.3.0
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Tauri app
        run: pnpm tauri build
        env:
          NEXT_PUBLIC_MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Alpha
          name: "HellCore Launcher v0.0.1 (Alpha)"
          draft: false
          prerelease: true
          files: |
            src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
