name: Build and Release HellCore Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - "Alpha"

jobs:
  build-alpha:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout HellCore Launcher
        uses: actions/checkout@v4
        with:
          repository: hell-core/hellcore-launcher
          ref: master
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1

      - name: Update and install system dependencies for Tauri (GTK/GLib/WebKit/libsoup)
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
            libgtk-3-dev \
            libglib2.0-dev \
            pkg-config \
            build-essential \
            libssl-dev \
            libdbus-1-dev \
            libgdk-pixbuf2.0-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.3.0
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build HellCore app
        run: pnpm tauri build
        env:
          NEXT_PUBLIC_MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Alpha
          name: "HellCore Launcher v0.0.1 (Alpha)"
          draft: false
          prerelease: true
          overwrite_files: true
          files: |
            src-tauri/target/release/bundle/HellCore-${{ github.ref_name }}-amd64.deb
            src-tauri/target/release/bundle/HellCore-${{ github.ref_name }}-x86_64.rpm
            src-tauri/target/release/bundle/hellcore-${{ github.ref_name }}.png
            src-tauri/target/release/bundle/HellCore.desktop

