name: Build and Release HellCore Launcher

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - "Alpha"

jobs:
  build-alpha:
    runs-on: ubuntu-latest

    steps:
      # 👇 Checkout the private repo with a Personal Access Token
      - name: Checkout HellCore Launcher
        uses: actions/checkout@v4
        with:
          repository: HELL-CORE/hellcore-launcher
          token: ${{ secrets.PAT_TOKEN }} # Must be set in repo secrets
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Alpha
          name: "HellCore Launcher v0.0.1 (Alpha)"
          draft: false
          prerelease: true
          files: |
            src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
